# Backend için Dockerfile

# Python 3.9 kullanıyoruz
FROM python:3.9-slim

# Çalışma dizinini oluştur
WORKDIR /app

# Gereksinim dosyasını çalışma dizinine kopyala
COPY requirements.txt .

# Gereksinimleri kur
RUN pip install --no-cache-dir -r requirements.txt

# Tüm uygulama dosyalarını çalışma dizinine kopyala
COPY . .

# Uvicorn sunucusunu başlatmak için komut
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
